'use strict';

const path = require('path');
const os = require('os');
const fs = require('fs-extra');

const PROJECT_ROOT = path.resolve(__dirname, '../../..');
const BUNDLED_ANDROID_SDK = path.join(PROJECT_ROOT, 'android-sdk');
const DEFAULT_ANDROID_SDK = path.join(
    os.homedir(),
    'AppData',
    'Local',
    'Android',
    'Sdk'
);

async function prepareAndroidEnv(shellDir) {
    const sdkDir = await resolveAndroidSdkDir();
    await writeLocalProperties(shellDir, sdkDir);

    const javaHome = await resolveJavaHome();

    return {
        sdkDir,
        javaHome,
    };
}

async function resolveAndroidSdkDir() {
    const candidates = [
        process.env.ANDROID_SDK_ROOT,
        process.env.ANDROID_HOME,
        BUNDLED_ANDROID_SDK,
        DEFAULT_ANDROID_SDK,
    ].filter(Boolean);

    for (const candidate of candidates) {
        if (await looksLikeAndroidSdk(candidate)) {
            return path.resolve(candidate);
        }
    }

    throw new Error(
        '未找到 Android SDK。\n' +
        '  请先安装 Android Studio / Android SDK，并满足以下任一条件：\n' +
        '  1. 设置 ANDROID_SDK_ROOT 或 ANDROID_HOME 环境变量\n' +
        `  2. 将便携 Android SDK 放到项目根目录：${BUNDLED_ANDROID_SDK}\n` +
        `  3. 使用 Android Studio 默认路径：${DEFAULT_ANDROID_SDK}`
    );
}

async function resolveJavaHome() {
    if (process.env.JAVA_HOME && await fs.pathExists(process.env.JAVA_HOME)) {
        return path.resolve(process.env.JAVA_HOME);
    }

    const bundledRoot = path.join(PROJECT_ROOT, 'jdk17');
    if (!(await fs.pathExists(bundledRoot))) {
        return undefined;
    }

    const entries = await fs.readdir(bundledRoot);
    for (const entry of entries) {
        const candidate = path.join(bundledRoot, entry);
        if (await fs.pathExists(path.join(candidate, 'bin', 'java.exe'))) {
            return candidate;
        }
    }

    return undefined;
}

async function looksLikeAndroidSdk(dir) {
    if (!dir) return false;

    const checks = [
        path.join(dir, 'platforms'),
        path.join(dir, 'build-tools'),
        path.join(dir, 'platform-tools'),
    ];

    for (const item of checks) {
        if (!(await fs.pathExists(item))) {
            return false;
        }
    }

    return true;
}

async function writeLocalProperties(shellDir, sdkDir) {
    const filePath = path.join(shellDir, 'local.properties');
    const escapedSdkDir = sdkDir.replace(/\\/g, '\\\\');
    const content =
        '# This file is generated by Web2Blue CLI.\n' +
        '# It points Gradle to the local Android SDK directory.\n' +
        `sdk.dir=${escapedSdkDir}\n`;

    await fs.writeFile(filePath, content, 'utf8');
}

module.exports = {
    prepareAndroidEnv,
};
